import { createRequire } from 'module';
const require = createRequire('/home/user/transaction-simulation-mobile-app/');
const pw = require('playwright');
const out = process.argv[2];
const b = await pw.chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const shot = (n) => p.screenshot({ path: `${out}/${n}.png` });
const tab = (t) => p.getByText(t, { exact: true }).last().click();
await p.goto('http://localhost:8099');
await p.waitForTimeout(800);
await shot('01-login');
await p.getByPlaceholder('Jane Doe').fill('Jane Doe');
await p.getByText('Enter sandbox').click();
await p.waitForTimeout(400);
await shot('02-home-empty');
await tab('Send');
await shot('03-send-form');
await p.getByText('+ New beneficiary').click();
await shot('04-send-new-beneficiary');
await p.getByText('+ New beneficiary').click();
await p.getByPlaceholder('0.00').fill('50000');
await p.getByText('Send', { exact: true }).first().click();
await shot('05-result-allowed');
await p.getByText('Done').click();
await p.getByPlaceholder('0.00').fill('600000');
await p.getByText('Send', { exact: true }).first().click();
await shot('06-result-flagged');
await p.getByText('Done').click();
await p.getByPlaceholder('0.00').fill('300000');
await p.getByText('Iran').click();
await p.getByText('Send', { exact: true }).first().click();
await shot('07-result-blocked');
await p.getByText('Done').click();
await tab('Home'); await shot('08-home-with-activity');
await tab('Activity'); await shot('09-activity');
await tab('Monitoring'); await shot('10-monitoring-alerts');
await p.mouse.wheel(0, 900); await p.waitForTimeout(300); await shot('11-monitoring-rules');
await b.close();
